### DISCUSSION TITLE
Can I use bat to colorize command output ?

### DISCUSSION THREAD

**Discussion by rexackermann** [sharkdp/bat#2601] [Q&A] [answered]
To put it simply can bat do this:
![Screenshot from 2023-06-21 15-51-38](https://github.com/sharkdp/bat/assets/61972253/6d03f4d7-8944-4e2a-a0bd-442016748212)

I used [grc](https://github.com/garabik/grc) to colorize output of lsblk here ? Can it be done by bat as well ? How ?

Thanks in advance.

**Comment by keith-hall** [comment, marked as answer]
```sh
lsblk | bat -l fstab
```

**Reply by rexackermann** [reply]
Thanks for the quick reply.Is it possible make it auto detect things like this.And also colorize columns in different colors and stuff with just plain text.

**Reply by keith-hall** [reply]
`bat` is designed to auto detect many different file types, but output from arbitrary command line tools not so much.
It may be possible to adapt the CSV syntax definition to make one that will treat any whitespace as a column separator, but it will not work properly if a column can contain whitespace.

Such a syntax could look like this:
```yaml
%YAML 1.2
---
# See http://www.sublimetext.com/docs/3/syntax.html
name: Whitespace Separated Values
scope: text.wsv
first_line_match: ^NAME\s+MAJ:MIN\s+
variables:
  field_separator: (?:[ \t]+)
  record_separator: (?:$\n?)
contexts:
  main:
    - meta_include_prototype: false
    - match: '^'
      set: unknown-separated-main

  unknown-separated-main:
    - include: record_separator
    - match: ''
      push:
        - field_or_record_separator
        - field4
        - field_or_record_separator
        - field3
        - field_or_record_separator
        - field2
        - field_or_record_separator
        - field1

  record_separator_pop:
    - match: (?={{record_separator}})
      pop: true

  record_separator:
    - meta_include_prototype: false
    - match: '{{record_separator}}'
      scope: punctuation.terminator.record.csv
      pop: true

  field_or_record_separator:
    - meta_include_prototype: false
    - include: record_separator_pop
    - match: '{{field_separator}}'
      scope: punctuation.separator.sequence.csv
      pop: true

  field_contents:
    - match: '"'
      scope: punctuation.definition.string.begin.csv
      push: double_quoted_string

    - include: record_separator_pop
    - match: (?={{field_separator}})
      pop: true

  double_quoted_string:
    - meta_include_prototype: false
    - meta_scope: string.quoted.double.csv
    - match: '""'
      scope: constant.character.escape.csv
    - match: '"'
      scope: punctuation.definition.string.end.csv
      pop: true

  field1:
    - meta_content_scope: meta.field-1.csv support.type
    - include: field_contents
  field2:
    - match: ''
      set:
        - meta_content_scope: meta.field-2.csv support.function
        - include: field_contents
  field3:
    - match: ''
      set:
        - meta_content_scope: meta.field-3.csv constant.numeric
        - include: field_contents
  field4:
    - match: ''
      set:
        - meta_content_scope: meta.field-4.csv keyword.operator
        - include: field_contents
```

You would need to save this as a `.sublime-syntax` file in your `bat` cache folder, and get `bat` to rebuild the binary assets. There's documentation which assumes you are using a git repo here, which may help: https://github.com/sharkdp/bat#adding-new-syntaxes--language-definitions

I'm not sure the best way for it to detect that it should use this syntax. Likely you'd want https://github.com/sharkdp/bat/issues/1341 to be implemented so that if it can't detect it as anything else, it would use this one.

Another potential option would be if you know the length of each column in advance, but you'd have to create a new syntax definition for each tool which outputs fixed width columns. Really, `bat`/ the `sublime-syntax` style of highlighting wasn't designed for this use-case - likely `grc` is a better fit here.
