### ISSUE TITLE
Option to hide secrets/passwords

### ISSUE THREAD

**Issue by ChocolateOverflow** [sharkdp/bat#1634]
I'd like to have a  flag to hide secrets and passwords. This can be done by matching keywords like "pass", "key" and "secret".

When a variable/token name matches one of the keywords, their value should be hidden with asterisks like passwords. For example, using `bat` on a YAML  file:

```yaml
# bat config.yaml
setting: "you can read this"
oauth_token: ********
```
