### ISSUE TITLE
Cannot get the cache directory path for `HighlightingAssets::from_cache`

### ISSUE THREAD

**Issue by rhysd** [sharkdp/bat#1917]
**Describe the bug you encountered:**

I'm using `bat` as library. `HighlightingAssets` provides two ways to initialize assets, `from_binary` and `from_cache`. However, `bat` crate does not provide a way to get the cache directory path.

**What did you expect to happen instead?**

I'd like `bat` crate to provide some API to return cache directory path.

**How did you install `bat`?**

```toml
[dependencies]
bat = { version = "0.18.3", default-features = false }
```

in my project's Cargo.toml

---

**bat version and environment**

- bat: 0.18.3
- OS: macOS 10.15
