### ISSUE TITLE
.weechatlog files

### ISSUE THREAD

**Issue by eggbean** [sharkdp/bat#2046]
**Syntax:**
`.weechatlog` (WeeChat log files)

WeeChat is a pretty popular terminal-based IRC client. https://github.com/weechat/weechat

I tried looking around for `.sublime-syntax` files to use, but could not find any.

The format of the files is quite simple, so should not be difficult for somebody who knows how to make these syntax files.

eg.

    2022-01-27 19:49:01     mbrgm   hi! when running `jseval -f`, is there a way to pass a parameter to the file?
    2022-01-27 19:49:28     mbrgm   not _as_, but to the code running _in_ the files
    2022-01-27 19:49:30     mbrgm   ?

It is simply <date> <time> <nick> <message>

**Comment by keith-hall** [comment]
Hi, do I understand your expectations correctly that the dates and times should get highlighted, and the rest of the line would be treated as Markdown?

**Comment by eggbean** [comment]
Well if the date was a sort of slightly more subdued colour and the nick a different colour and then the message content most readable, that would make it easier to read. If the nicks could be different random colours based on some sort of number derived from the nick, as done in weechat itself (with certain scripts) that would make it even more readable, as the colour would be (mostly) unique for each nick. There isn't any markdown though.

**Comment by eggbean** [comment]
I just realised that my last line above did not render. It should have been:

    It is simply <date><time>  <nick>  <message>

**Comment by eggbean** [comment]
There is actually another type of meta line as well, where the nick is replaced with two hyphens. Here is a sample log:

http://sprunge.us/tWsO32

**Comment by keith-hall** [comment]
> If the nicks could be different random colours based on some sort of number derived from the nick, as done in weechat itself (with certain scripts) that would make it even more readable, as the colour would be (mostly) unique for each nick.

Unfortunately, `syntect` - the syntax highlighting library we are using - doesn't currently support what Sublime Text calls ["Hashed Syntax Highlighting"](http://www.sublimetext.com/docs/color_schemes.html#hashed_syntax_highlighting). I believe the closest tracking issue we have is https://github.com/trishume/syntect/issues/244.

So, you can have a syntax definition and color scheme in ST which would achieve what you want, but it won't look so good in `bat` for the time being.

```yaml
%YAML 1.2
---
# See http://www.sublimetext.com/docs/3/syntax.html
file_extensions:
  - weechatlog
scope: text.weechatlog
variables:
  ipv4_part: (?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)
contexts:
  main:
    - match: '^'
      push: beginning-of-line

    - include: scope:text.log#ip_addresses
    - include: scope:text.log#numbers

  beginning-of-line:
    - include: scope:text.log#dates
    - match: '--'
      scope: punctuation.definition.comment.weechatlog
      push: inside-line-comment
    - match: (?=\S)
      set: nickname

  nickname:
    - match: \S+
      scope: source meta.nickname.weechatlog support.type.weechatlog
      pop: true

  inside-line-comment:
    - meta_scope: comment.line.double-dash.weechatlog
    - match: $\n?
      pop: true
```

how the sample log looks like in ST with the "Celeste" color scheme with the above syntax definition:
![image](https://user-images.githubusercontent.com/11882719/151617403-df3e5706-14a3-4742-aea6-427245765532.png)
