### ISSUE TITLE
Question about adding support using sublime-syntax files. 

### ISSUE THREAD

**Issue by hartmms** [sharkdp/bat#255]
I'm trying to setup bat to highlight custom tool log files I have.  (Error|ERROR, WARN|Warning, etc).  There is really no fancy syntax in these logfiles.  I just need it to highlight a single line in red if it has the "error" regular expression I create or highlight it yellow if a single like has the "warning" regexp. 

I can't seem to get it to work, but I feel I'm missing something fundamental about how sublime-syntax files work. I have this right now:

```
%YAML 1.2
---
name: log
comment: log files
file_extensions:
  - log
  - logv
scope: text.plain
contexts:
  main:
    - match: WARN|Warning|WARNING
      scope: punctuation.definition.string.begin.tcl
    - match: ERR|ERROR|Error
      scope: keyword.other.tcl

  punctuation.definition.string.begin.tcl:
    - match: '[\r\n]'
      pop: true

  keyword.other.tcl:
    - match: '[\r\n]'
      pop: true
```

Can I re-purpose scopes like this?  I tried to make my own scopes "warning" and "error", but I'm in even more over my head making a theme file with info on how to color the different scopes.
