### ISSUE TITLE
Support for CITATION.cff aka citation files from GitHub

### ISSUE THREAD

**Issue by SamuelLarkin** [sharkdp/bat#3003]
Hi,
  I would like to suggest supporting `.cff` files which are the file format for GitHub citation (`CITATION.cff`).  According to [Citation File Format (CFF)](https://citation-file-format.github.io/about/#:~:text=Citation%20File%20Format%20is%20a,%2Fcitation%2Dfile%2Dformat.),
```
Citation File Format is a human- and machine-readable file format in [YAML 1.2](http://www.yaml.org/spec/1.2/spec.html) which provides citation metadata for software.
```

### cff Example

```yaml
cff-version: 1.2.0
message: "If you use this software, please cite it as below."
authors:
- family-names: "Lisa"
  given-names: "Mona"
  orcid: "https://orcid.org/0000-0000-0000-0000"
- family-names: "Bot"
  given-names: "Hew"
  orcid: "https://orcid.org/0000-0000-0000-0000"
title: "My Research Software"
version: 2.0.4
doi: 10.5281/zenodo.1234
date-released: 2017-12-18
url: "https://github.com/github-linguist/linguist"
```

### Resources

* [What is a CITATION.cff file?](https://citation-file-format.github.io/)
* [The Citation File Format lets you provide citation metadata for software or datasets in plaintext files that are easy to read by both humans and machines.](https://github.com/citation-file-format/citation-file-format)
* [About CITATION files on Github](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files)
* [Sublime HQ - [YAML] Add CITATION.cff file extension](https://github.com/sublimehq/Packages/pull/3947)
