### ISSUE TITLE
Add support for `templ` syntax

### ISSUE THREAD

**Issue by mfinelli** [sharkdp/bat#3134]
I wanted to see about adding support for the `templ` syntax. It doesn't have many packagecontrol downloads (though I suspect it's because fewer and fewer people use sublime text these days) but Github has support for .templ files so I wanted to see if we could add it anyway. If so I will open a pull request, if not then I will just need to install it locally. Cheers

**Syntax:**
templ (https://templ.guide / https://github.com/a-h/templ)

**Guideline Criteria:**
https://packagecontrol.io/packages/Templ%20(go)

**Comment by CoreyCole** [comment]
https://packagecontrol.io/packages/Templ%20(go) this did not work for me. I was able to hack around it with:

```
cat > ~/.config/bat/syntaxes/templ.sublime-syntax <<'EOF'
%YAML 1.2
---
name: Templ
file_extensions:
  - templ
scope: source.go.templ

contexts:
  main:
    # Templ component declaration: templ Name(args) {
    - match: \btempl\s+([[:alpha:]_][[:alnum:]_]*)
      captures:
        0: keyword.declaration.templ
        1: entity.name.function.templ
      push: templ-signature

    # Legacy script template declaration: script Name(args) {
    - match: \bscript\s+([[:alpha:]_][[:alnum:]_]*)
      captures:
        0: keyword.declaration.templ
        1: entity.name.function.templ
      push: script-signature

    # Top-level Go: package, imports, funcs, vars, types, etc.
    - include: scope:source.go

  templ-signature:
    - meta_scope: meta.templ.signature
    - match: '\{'
      scope: punctuation.section.block.begin.templ
      set: templ-block
    - include: scope:source.go

  script-signature:
    - meta_scope: meta.templ.script.signature
    - match: '\{'
      scope: punctuation.section.block.begin.templ
      set: js-block
    - include: scope:source.go

  templ-block:
    - meta_scope: meta.templ.block

    # End of templ block.
    - match: '\}'
      scope: punctuation.section.block.end.templ
      pop: true

    # Explicit CSS blocks inside templ HTML.
    - match: '(<style\b[^>]*>)'
      captures:
        1: punctuation.definition.tag.begin.html
      push: css-block

    # Explicit JS blocks inside templ HTML.
    - match: '(<script\b[^>]*>)'
      captures:
        1: punctuation.definition.tag.begin.html
      push: html-script-block

    # Go expressions in templ nodes: { foo }, { if x }, etc.
    - match: '\{'
      scope: punctuation.section.embedded.begin.go
      push: go-embedded

    # Component calls: @Button(...)
    - match: '@'
      scope: punctuation.section.embedded.begin.go
      push: go-at-embedded

    # HTML tags and attributes.
    - include: scope:text.html.basic

  go-embedded:
    - meta_scope: source.go.embedded.templ
    - match: '\}'
      scope: punctuation.section.embedded.end.go
      pop: true
    - include: scope:source.go

  go-at-embedded:
    - meta_scope: source.go.embedded.templ

    # Return to HTML-ish parsing when the component call has emitted markup.
    - match: '(?=\s*<)'
      pop: true

    # Avoid eating the rest of the file if the line ends.
    - match: '$'
      pop: true

    # Nested templ block after a component call.
    - match: '\{'
      scope: punctuation.section.block.begin.templ
      push: templ-block

    - include: scope:source.go

  css-block:
    - meta_scope: source.css.embedded.html
    - match: '(</style>)'
      captures:
        1: punctuation.definition.tag.end.html
      pop: true

    # Templ/Go expressions inside CSS, if present.
    - match: '\{'
      scope: punctuation.section.embedded.begin.go
      push: go-embedded

    - include: scope:source.css

  html-script-block:
    - meta_scope: source.js.embedded.html
    - match: '(</script>)'
      captures:
        1: punctuation.definition.tag.end.html
      pop: true

    # Templ/Go expressions inside JS, if present.
    - match: '\{'
      scope: punctuation.section.embedded.begin.go
      push: go-embedded

    - include: scope:source.js

  js-block:
    - meta_scope: source.js.embedded.templ
    - match: '\}'
      scope: punctuation.section.block.end.templ
      pop: true
    - include: scope:source.js
EOF
```

```
bat cache --build
```

<img width="791" height="777" alt="Image" src="https://github.com/user-attachments/assets/674144b3-a5ff-4d89-8b02-0da3bdbe0aeb" />
