### ISSUE TITLE
how to install on CentOS 7?

### ISSUE THREAD

**Issue by iTonyYo** [sharkdp/bat#325]

**Comment by sharkdp** [comment]
We provide binary releases for every major platform: https://github.com/sharkdp/bat/releases

**Comment by sharkdp** [comment]
For CentOS, you probably need the `bat-vX.Y.Z-x86_64-unknown-linux-musl.tar.gz` tarballs

**Comment by Mebus** [comment]
> We provide binary releases for every major platform: https://github.com/sharkdp/bat/releases

I don't see a rpm package, so you don't provide a release for every major platform....

I would like to install it on Fedora.

Mebus

**Comment by sharkdp** [comment]
@Mebus With platform, I mean CPU architecture and operating system.

Packaging for different distributions is an entirely different story and there are open tickets for this already: #317.

**Comment by iTonyYo** [comment]
@sharkdp **THANKS A LOT!** 😃 

According to what you said, I installed it on CentOS 7 like this.

**Download [`bat-vX.Y.Z-x86_64-unknown-linux-musl.tar.gz`](https://github.com/sharkdp/bat/releases/download/v0.7.1/bat-v0.7.1-x86_64-unknown-linux-musl.tar.gz),**

```shell
wget -O bat.zip https://github.com/sharkdp/bat/releases/download/v0.7.1/bat-v0.7.1-x86_64-unknown-linux-musl.tar.gz

tar -xvzf bat.zip -C /usr/local

cd /usr/local && mv bat-v0.7.1-x86_64-unknown-linux-musl bat

cd ~
```

**add alias to `~/.zshrc`,**
```conf
alias bat="/usr/local/bat/bat"
```

and then I can use **`bat`** command anywhere!

**Comment by mlopezcoria** [comment]
> @sharkdp **THANKS A LOT!** smiley
> 
> According to what you said, I installed it on CentOS 7 like this.
> 
> **Download [`bat-vX.Y.Z-x86_64-unknown-linux-musl.tar.gz`](https://github.com/sharkdp/bat/releases/download/v0.7.1/bat-v0.7.1-x86_64-unknown-linux-musl.tar.gz),**
> 
> ```shell
> wget -O bat.zip https://github.com/sharkdp/bat/releases/download/v0.7.1/bat-v0.7.1-x86_64-unknown-linux-musl.tar.gz
> 
> tar -xvzf bat.zip -C /usr/local
> 
> cd /usr/local && mv bat-v0.7.1-x86_64-unknown-linux-musl bat
> 
> cd ~
> ```
> 
> **add alias to `~/.zshrc`,**
> 
> ```
> alias bat="/usr/local/bat/bat"
> ```
> 
> and then I can use **`bat`** command anywhere!

On CentOS 7 I followed you installation instructions but when I run bat I get this error:
`zsh: exec format error: /usr/local/bat/bat`

How I "installed" bat:
```
wget -O bat.zip https://github.com/sharkdp/bat/releases/download/v0.8.0/bat-v0.8.0-aarch64-unknown-linux-gnu.tar.gz
tar -xvzf bat.zip -C /usr/local
mv /usr/local/bat-v0.8.0-aarch64-unknown-linux-gnu /usr/local/bat
alias bat='/usr/local/bat/bat'
```
What am I doing wrong?

Thanks in advance!

**Comment by frank0718** [comment]
wget https://github.com/sharkdp/bat/releases/download/v0.7.1/bat-v0.7.1-x86_64-unknown-linux-musl.tar.gz -O - |tar -xvzf - -C /usr/local/bin && mv /usr/local/bin/bat-v0.7.1-x86_64-unknown-linux-musl/bat /usr/local/bin/bat

**Comment by ranebull** [comment]
I write playbook for RHEL-based distributions:
```yml
- name: get bat latest version
  block:
    - shell: curl --silent "https://api.github.com/repos/sharkdp/bat/releases/latest" | grep -Po '"tag_name"':' "\K.*?(?=")' warn=false
      register: latest_release
    - get_url:
        url: https://github.com/sharkdp/bat/releases/download/{{latest_release.stdout}}/bat-{{latest_release.stdout}}-x86_64-unknown-linux-musl.tar.gz
        dest: /tmp
    - unarchive:
        src: bat-{{latest_release.stdout}}-x86_64-unknown-linux-musl.tar.gz
        dest: /tmp
    - copy:
        src: /tmp/bat-{{latest_release.stdout}}-x86_64-unknown-linux-musl/
        dest: /usr/local/bat/
        mode: preserve
    - lineinfile:
        path: ~/.bashrc
        line: "alias bat='/usr/local/bat/bat'"
        insertafter: 'mv'
    - find:
        paths: /tmp
        file_type: any
        patterns: bat*
      register: bat_files_delete      
    - file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ bat_files_delete.files }}"
```
